apps:
  vars:
    ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh_key
  hosts:
    jenkins:
      ansible_host: 192.168.60.100
    prod:
      ansible_host: 192.168.60.150

monitor:
  vars:
    ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh_key
  hosts:
    monitor:
      ansible_host: 192.168.60.110